# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- master


resources:
  repositories:
  - repository: multisocialpost # The name used to reference this repository in the checkout step
    type: github
    endpoint: zahasoftware
    name: zahasoftware/multisocialpost
    ref: $(Build.SourceBranchName)

pool:
  vmImage: 'ubuntu-latest'

  
workspace:
  clean: all # what to clean up before the job

steps:

- checkout: self
  path: multisocialpostgui/
- checkout: multisocialpost

- task: CmdLine@2
  inputs:
    script: |
      mv $(Build.SourcesDirectory)/../multisocialpostgui $(Build.SourcesDirectory)/multisocialpostgui
      pwd
      ls
      ls $(Build.SourcesDirectory)/multisocialpostgui/ZS.MultiSocialPostsGui.Angular/

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      echo "Creating Image"
      
      push-location $(Build.SourcesDirectory)/multisocialpostgui/ZS.MultiSocialPostsGui.Angular/
      ls
      docker-compose build multisocialpostgui 

      echo "Listnando imagenees"     
      docker images
            
      $version = $(cat docker-compose.yml  | grep "multisocialpostgui:" | awk -F':'  '{print $3}')
      #echo "Guardando IMAGEN $version"
      
      docker save -o asdf.tar ubuntu:18.04
      docker save -o asdf_ctm.tar multisocialpostgui:1.0
      
      echo "LS TARS"
      mkdir -p images
      mv *.tar images/
      mv *.yml images/
      ls images
      
      mv images $(Build.SourcesDirectory)/images 

      pop-location


- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: 'images'
    includeRootFolder: true
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true


- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'

